# Generated by Django 6.0.3 on 2026-05-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField()),
                ('category', models.CharField(choices=[('general', 'General MMA'), ('fighter', 'Fighter News'), ('preview', 'Event Previews'), ('results', 'Fight Results')], max_length=20)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['category', '-published_at'], name='news_articl_categor_d69a9f_idx')],
            },
        ),
    ]
