"""
AI Assistant app views — chat, program generation, program download.
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views import View

from apps.ai_assistant.models import TrainingProgram
from apps.ai_assistant.services import (
    IncompleteParamsError,
    generate_training_program,
    send_message,
)


class ChatView(LoginRequiredMixin, View):
    """Handle GET to render the chat page and POST to send a chat message."""

    def get(self, request, *args, **kwargs):
        return render(request, "ai_assistant/chat.html")

    def post(self, request, *args, **kwargs):
        try:
            message = request.POST.get("message", "")
            # Ensure the session exists so session_key is not None
            if not request.session.session_key:
                request.session.create()
            reply = send_message(
                session_key=request.session.session_key,
                user=request.user,
                message=message,
            )
            return JsonResponse({"reply": reply})
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)


class GenerateProgramView(LoginRequiredMixin, View):
    """Handle GET to render the program generation form and POST to generate."""

    def get(self, request, *args, **kwargs):
        return render(request, "ai_assistant/generate_program.html")

    def post(self, request, *args, **kwargs):
        params = {
            "goals": request.POST.get("goals", ""),
            "fitness_level": request.POST.get("fitness_level", ""),
            "days_per_week": request.POST.get("days_per_week", ""),
            "limitations": request.POST.get("limitations", ""),
        }
        try:
            program = generate_training_program(user=request.user, params=params)
            return JsonResponse(
                {
                    "program_id": program.pk,
                    "download_url": f"/ai/programs/{program.pk}/download/",
                }
            )
        except IncompleteParamsError as e:
            return JsonResponse(
                {"error": str(e), "clarification_needed": True}, status=400
            )


class ProgramDownloadView(LoginRequiredMixin, View):
    """Serve the PDF file for a training program owned by the requesting user."""

    def get(self, request, pk, *args, **kwargs):
        program = get_object_or_404(TrainingProgram, pk=pk, user=request.user)
        return FileResponse(
            program.pdf_file.open("rb"),
            content_type="application/pdf",
            as_attachment=True,
            filename=f"training_program_{pk}.pdf",
        )


class ProgramListView(LoginRequiredMixin, View):
    """Display all training programs generated by the requesting user."""

    def get(self, request, *args, **kwargs):
        programs = TrainingProgram.objects.filter(user=request.user).order_by(
            "-generated_at"
        )
        return render(request, "ai_assistant/program_list.html", {"programs": programs})
